### ISSUE TITLE
Macro is lost after closing Word

### ISSUE THREAD

**Issue by chaoscreater** [analyticsinmotion/add-chatgpt-to-microsoft-word#4]
I got everything working correctly, but Word seems to lose the macro after it is closed. Is there a way to make this stick?

**Comment by chaoscreater** [comment]
Actually never mind, I'm stupid. Got it working.

**Comment by losparviero** [comment]
How did you fix it? I'm having the same issue

**Comment by rossarmstrong** [comment]
Hi @losparviero, we have had this issue raised a couple of times. On both occasions, re-importing the VBA script file and re-linking to the ribbon button got it working again. We are still looking at the underlying cause of this issue. Could you please let us know what version of Word/Office you are using? Cheers

**Comment by rossarmstrong** [comment]
Hi again, we are sorry to hear that it is still having issues. The two cases we have seen from other users were only affected temporarily, and both were on Office/Word 2016. Once the macro files were reimported, they didn't disappear again. We have been unable to replicate the issue on our side. However, we have seen a lot of articles on macros disappearing in general. I would do search to find any articles that may be similar to your setup. For example, here are two articles on the Microsoft forum we were looking at: <a href="https://answers.microsoft.com/en-us/msoffice/forum/all/word-deletes-all-my-macros-about-once-a-month/4c86d021-9751-4de9-84dc-78044b0d019d">Word DELETES all my macros about once a month</a> and <a href="https://answers.microsoft.com/en-us/msoffice/forum/all/normal-template-wiped-again/a96dba06-68f7-40e8-a1a2-55ddef1bcca7">Normal template wiped, again</a>.

Keep us posted on how you go and if you can/can't find a fix to your issue.

**Comment by ilovefreesw** [comment]
Using Office LTSC 2021 ... it gets delinked again and again.

![image](https://github.com/analyticsinmotion/add-chatgpt-to-microsoft-word/assets/77317006/a623f1b2-3e1d-4844-8533-e9349bdcb334)

I have to import it again in the Visual Basic and then use it.

**Comment by rossarmstrong** [comment]
Hi @ilovefreesw, thank you for letting us know you are having an issue. Can you tell us what macro settings you have selected? You should be able to find this in the Developer tab and then click Macro Security. Thanks

**Comment by ilovefreesw** [comment]
![image](https://github.com/analyticsinmotion/add-chatgpt-to-microsoft-word/assets/77317006/899e8a01-9ba9-4d5b-a4f7-f8ecb15fe48a)

**Comment by rossarmstrong** [comment]
Try to Import the .bas again. However, this time before clicking File > Import, make sure you have the Normal Project selected first (see image below)

![Error Fix 2](https://github.com/analyticsinmotion/add-chatgpt-to-microsoft-word/assets/52817125/9cf272ce-2e96-4bd0-a4fd-617b0c4f8487)

Try this and let us know how you go

**Comment by ilovefreesw** [comment]
Yes it works this way now. Thanks.

**Comment by Simgauit** [comment]
![image](https://github.com/analyticsinmotion/add-chatgpt-to-microsoft-word/assets/172811712/3ae4eb86-af5b-48c1-8433-1e9a1338335b)
Hi,
I have re imported the .bas file. 
But now a different error, open AI server error.
No actual issue with server as other program is working.
I have tried deleteing previous key and repeated the process with new key and restarted, but no change.
sorry to bother you. I ma not sure where i am getting it wrong.
BW
S
